// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdbrkxlmrzvhwdegzlqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkYnJreGxtcnp2aHdkZWd6bHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MzAwOTQsImV4cCI6MjA3NjUwNjA5NH0.4X97L1eLX6frGlVo7ezQt_qjRRKqjnGM5mBZZreVOHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});